language: python
python:
  - 2.7
install:
  - pip install -r tests_requirements.txt
  # - pip install coveralls
script:
  - coverage run -m unittest discover
  - pycodestyle canvasapi tests
  - pyflakes canvasapi tests
# after_success:
#   - coveralls
